### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by EhWhoAmI** [TheOpenSpaceProgram/osp-magnum#101]
Adding a unit testing library, such as [Boost.Test](https://www.boost.org/doc/libs/1_75_0/libs/test/doc/html/index.html) or [gtest](https://github.com/google/googletest), and testing the systems and other things, will be helpful to guarantee behavior.

**Comment by Capital-Asterisk** [comment]
The Corrade library used by Magnum has one built in, it looks pretty cool.

https://doc.magnum.graphics/corrade/testsuite.html

**Comment by Capital-Asterisk** [comment]
Google tests added on #143
