### ISSUE TITLE
Enums for stock shaders

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#107]
Right now, shaders are described by an `ACompShader` which stores a function pointer that is used to invoke the shader on some entity. The downside to this arrangement is that it leaks graphics API dependence slightly into the rest of the codebase. For now, the default Phong shader is fallen back on when the function pointer value is `nullptr`, but a better approach described by @Capital-Asterisk would be to create an enumeration of stock shader types like
```cpp
enum class EShader
{
    Phong = 0,
    PBR = 1,
    Planet = 2,
    ChemRocketExhaust = 3,
    JetEngineExhaust = 4,
    Skybox =  5,
    // ...
};
```
and provide an interface that accepts the enum when the user attaches a shader:
```cpp
reg.emplace<ACompVisible>(ent);
reg.emplace<ACompShader>(ent, EShader::Phong);
```
which may be achieved by an `ACompShader` constructor like
```cpp
ACompShader::ACompShader(EShader shader)
{
    switch (shader)
    {
    case EShader::Phong:
        m_drawFnc = osp::shader::Phong::draw_entity;
        return;
    case EShader::PBR:
        // ...
    }
}
```
or some similar approach.

Specialized shaders whose function need not be exposed to the user (e.g. compute shaders) do not need to be included in the `EShader` enum.

**Comment by Capital-Asterisk** [comment]
ACompShader is dead, replaced by RenderGroups and materials.
