### ISSUE TITLE
Change the starting scene so that the rockets that are spawned are all in a somewhat stable orbit

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/osp-magnum#127]
It's OK if they eventually fall, as long as they can make 5-10 passes around the planet.

**Comment by Capital-Asterisk** [comment]
This sets a few goals. Right now, there's no "set velocity" for the physics engine; this needs to be implemented. Storing velocity data in the Universe is [already possible](https://github.com/TheOpenSpaceProgram/osp-magnum/blob/fbf0a19c2a01fbc0c302a9031fce01ec6b16fc80/src/osp/CoordinateSpaces/CartesianSimple.h#L80) but all are to 0 and are unused.

**Comment by Capital-Asterisk** [comment]
This test scene doesn't exist anymore
