### ISSUE TITLE
Get the compiler flag situation under control

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/osp-magnum#139]
Each compiler and platform and build type may need a different set of flags. Currently our main CMakeLists.txt allows for clang/GCC settings to be passed to MSVC in debug builds. Causing failures.

**Comment by jonesmz** [comment]
Really, these should be broken out into toolchain files, that would provide the best experience, i think.

**Comment by Capital-Asterisk** [comment]
Rather sure this isn't an issue anymore
