### ISSUE TITLE
All "systems" should be marked noexcept

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/osp-magnum#144]
Unless, of course, we want to allow this for some reason.

The noexcept keyword allows the compiler to omit a bunch of extra code that would normally be generated for a function. It's a performance optimization.

Additionally, lots of standard container types enable faster code paths if constructors and assignment operators are noexcept.

**Comment by Capital-Asterisk** [comment]
Tasks (aka: systems) are marked noexcept in top_worker.h since #214
```cpp
using TopTaskFunc_t = TopTaskStatus(*)(WorkerContext&, ArrayView<entt::any>) noexcept;
```
