### ISSUE TITLE
Beef up the the FunctionOrder class

### ISSUE THREAD

**Issue by Capital-Asterisk** [TheOpenSpaceProgram/osp-magnum#2]
## The FunctionOrder class:

After getting pissed at 'post update, update, pre update' from other game engines, and also KSP's TimingManager class, I decided to create the FunctionOrder class.

It calls a sequence of functions in a specific order, sorting them correctly based "before/after" rules. It handles cases like "this function must be called after the wire update, but before the physics update."

https://github.com/TheOpenSpaceProgram/osp-magnum/blob/3f11db3/src/osp/FunctonOrder.h

If we have std::functions A, B, and C, AfterABeforeB, AfterC, BeforeA with variable names explaining when the function should be called:

```cpp
FunctionOrder<void(void)> order;
std::function A, B, C, AfterABeforeB, AfterC, BeforeA;

//...

order.add("A",              "",     "",     A);
order.add("B",              "",     "",     B);
order.add("C",              "",     "",     C);
order.add("AfterABeforeB",  "A",    "B",    AfterABeforeB);
order.add("AfterC",         "C",    "",     AfterC);
order.add("BeforeA",        "",     "A",    BeforeA);
```

Calling `order.call()` will be equivalent to:

```cpp
BeforeA();
A();
AfterABeforeB();
B();
C();
AfterC();
```

Also note that functions in the order are reference counted, and order.add returns an RAII "FunctionOrderHandle" so technically the above code is invalid. The code that removes the functions when their ref count goes to 0 is not yet implemented.

FunctionOrder has no dependencies specific to OSP, and can be used for other projects.

## Use in OSP

The function order used by ActiveScene (aliased as UpdateOrder) calls ECS system functions.

Running the list_upd command while the application is running will list all the update functions called, with `// comments` added in to explain what they do
```
> list_upd
Update order:
* mach_usercontrol // MachineUserControl read user input
* wire // Wire propagation (not implemented)
* dbg_cam_vmod // DebugCameraController self-destruct function
* vehicle_modification // Handles new/removed/separated parts from vehicles
* planet_geo // PlanetA colliders and mesh update
* ff_gravity // Gravity ForceField apply forces
* mach_rocket // MachineRocket reads wire and applies forces
* physics // Physics World Update
* areascan // ActiveArea checks for Satellites to activate
* planet_phys // blank function 
* dbg_cam // DebugCameraController camera movement
```

Most of these functions will iterate through components, except for dbg_ ones.

It is also used for rendering, aliased as RenderOrder.

### It's Incomplete:

First off, this class is still incomplete. Reference counting doesn't do anything. There are also cases when it cannot insert a function because it's not able to re-order existing functions; for example:

```cpp
order.add("A",          "",     "",     A);
order.add("BeforeA1",   "",     "A",    BeforeA1);
order.add("BeforeA2",   "",     "A",    BeforeA2);

// order inside:
// * BeforeA1
// * BeforeA2
// * A

// BeforeA1 and BeforeA2 has to be swapped for this function to be inserted.
// This is not yet implemented
order.add("AfterBeforeA2_BeforeBeforeA1", "BeforeA2", "BeforeA1", whatever);
```

### Flexibility / Tagging:

Functions have things in common, such as ff_gravity and mach_rocket which both apply forces. What if a function needed to run only after all the forces have been applied? It shouldn't know anything about ff_gravity or mach_rocket, and their order isn't even guaranteed. It would be best to have some sort tag assigned to ff_gravity and mach_rocket that rules can be applied to. Maybe instead of having rules per-function, have tags that have rules, where these tags can be applied to the functions.

### Multithreading

A benefit of ECS is that it's really easy to multithread, and that was in mind while writing this class. Some functions can be called at the same time without racing or interfering with each other. ~~If two functions can be swapped without affecting the order, then they can be run in parallel.~~

Even better, it's possible to list per-function which components they read and write to. This turns out to be very similar to something developers of Overwatch have tried. This whole presentation is worth watching, but this part in particular: https://youtu.be/W3aieHjyNvw?t=2657

It may also be a good idea to pass the number of threads a system can used to the function calls, so that the optimal number of cores can be used.

It wouldn't be the simple old FunctionOrder anymore after changes like this.

**Comment by Capital-Asterisk** [comment]
I mentioned a tagging system, here's how it might go:

```

// A theoretical particle system
// This particle system uses components: Position, Velocity, Lifetime
// add(tags, function)

// "reads:"    tag means it reads a component's value
// "modifies:" tag means it modifies a component's value
// "allocate:" tag means it adds or removes components, and might reallocate the pool

// Deletes particles that have 0 lifetime
order.add({
    "ParticleDelete"
    "Particles",
    "modifies:Position",
    "modifies:Velocity",
    "modifies:Lifetime"}, &particle_new);

// Create new particles, set initial values based on some config
order.add({
    "ParticleNew",
    "Particles",
    "after:ParticleDelete",
    "allocates:Position",
    "allocates:Velocity",
    "allocates:Lifetime"}, &particle_new);

// Decay will decrement the particle's lifetimes
order.add({
    "ParticleDecay",
    "Particles",
    "before:ParticleVelocityPosition",
    "modifies:Lifetime"}, &particle_decay);

// Update position of particles
order.add({
    "ParticleVelocityPosition",
    "Particles",
    "reads:Velocity",
    "modifies:Position"
}, &particle_position);


// Somewhere else in a Render

// Render particles only after all the particle updating is done.
order.add({
    "RenderParticles",
    "Render",
    "after:Particles", // Call only after all the particle-related functions are done
    "reads:Position"}, &render_particles);


// Somewhere else, someone wants to add gravity to the particle system.

// Gravity modifies their velocities
order.add({
    "CustomParticleGravity",
    "Particles",
    "before:ParticleVelocityPosition",
    "modifies:Velocity"}, &custom_particle_gravity);

```

Resulting sorted function order will look like this (using the first tag as identifiers):
* ParticleDelete
* ParticleNew
* ParticleDecay
* CustomParticleGravity
* ParticleVelocityPosition
* RenderParticles

The "allocate," "modify," and "read" tags can be used for very optimized and dead simple multithreading. Number of threads a function uses can be passed as an argument. It's also possible to know which functions can be run concurrently without any race conditions, as the tags tell which components each function reads or modifies.

Setting up the FunctionOrder is not performance critical. Using multiple strings like this was mostly for readability. These tag strings only determine how the functions will be sorted initially.

**Comment by jonesmz** [comment]
This is very similar to "strands" from boost asio.

**Comment by jonesmz** [comment]
Another way to look at it is that you are describing a task graph  https://github.com/taskflow/taskflow

**Comment by jonesmz** [comment]
@z-adams does have most of the work for switching to task-flow here: https://github.com/z-adams/osp-magnum/tree/integrate-taskflow

As such, I'm assigning to him until he says otherwise.

**Comment by jonesmz** [comment]
@Capital-Asterisk Now that you've removed the function order class entirely from the engine, should this issue be closed?

**Comment by Capital-Asterisk** [comment]
> @Capital-Asterisk Now that you've removed the function order class entirely from the engine, should this issue be closed?

The problem has changed quite a bit, and most of the stuff I put on this issue may be impractical. A carefully arranged taskflow graph is likely the way to go, which should instead be a different issue.
