### ISSUE TITLE
issue while compiling

### ISSUE THREAD

**Issue by tigercoding56** [TheOpenSpaceProgram/osp-magnum#222]
this error happened on a raspberry pi running pop-os! 
while building (i just copied & pasted the build commands from readme.md file)
`gmake[1]: *** [CMakeFiles/Makefile2:2899: src/CMakeFiles/osp-magnum.dir/rule] Error 2
gmake: *** [Makefile:954: osp-magnum] Error 2
celleron56@takestatisticsandbecomeaactuary-undertoad ~/.rice [2]> 

`

**Comment by jonesmz** [comment]
We're going to need to see much more of the error output. The text you copied doesn't have any indication of the problem.

**Comment by Capital-Asterisk** [comment]
This looks like error happened during build, but configured just fine. Set the VERBOSE environment variable before building to get more output out of make:
```sh
export VERBOSE=1
```
We're not actively testing on any ARM machines at the moment, so I can't say the platform is fully supported. There isn't any platform-specific code in the project, but something in the build system or dependencies may break.

**Comment by tigercoding56** [comment]
> export VERBOSE=1

will try

**Comment by tigercoding56** [comment]
```
`keFiles/SDL2.dir/src/thread/pthread/SDL_systls.c.o CMakeFiles/SDL2.dir/src/thread/pthread/SDL_syssem.c.o CMakeFiles/SDL2.dir/src/misc/unix/SDL_sysurl.c.o CMakeFiles/SDL2.dir/src/haptic/dummy/SDL_syshaptic.c.o CMakeFiles/SDL2.dir/src/sensor/dummy/SDL_dummysensor.c.o CMakeFiles/SDL2.dir/src/filesystem/dummy/SDL_sysfilesystem.c.o CMakeFiles/SDL2.dir/src/locale/dummy/SDL_syslocale.c.o CMakeFiles/SDL2.dir/src/timer/dummy/SDL_systimer.c.o  -lm -lrt -L/usr/lib/aarch64-linux-gnu -lpulse-simple -pthread -lpulse -Wl,--no-undefined 
cd /home/celleron56/.rice/build-osp-magnum/3rdparty/SDL2 && /usr/bin/cmake -E cmake_symlink_library ../../Release/lib/libSDL2-2.0.so.0.2301.0 ../../Release/lib/libSDL2-2.0.so.0 ../../Release/lib/libSDL2-2.0.so
gmake[3]: Leaving directory '/home/celleron56/.rice/build-osp-magnum'
[ 43%] Built target SDL2
gmake[2]: Leaving directory '/home/celleron56/.rice/build-osp-magnum'
gmake[1]: *** [CMakeFiles/Makefile2:2899: src/CMakeFiles/osp-magnum.dir/rule] Error 2
gmake[1]: Leaving directory '/home/celleron56/.rice/build-osp-magnum'
gmake: *** [Makefile:954: osp-magnum] Error 2
`
```
here

**Comment by Capital-Asterisk** [comment]
Sorry for the month-long wait. The important part of the error is somewhere above what you posted; the tail end of the output here isn't enough information. 

It's going to take quite a bit of effort to get arm builds working, but thanks for trying.

**Comment by jonesmz** [comment]
Hey, haven't heard from you for a while.

Please reopen / comment on this if you are still having problems!
