### ISSUE TITLE
Get rid of std::cout and use some sort of logger

### ISSUE THREAD

**Issue by Capital-Asterisk** [TheOpenSpaceProgram/osp-magnum#3]
There's `std::cout`s all over the place. A proper logger or some sort should've been added earlier. Magnum or Corrade might have one built-in. There's many ways to do this, and also get rid of useless undescriptive prints because they're mostly just annoying.

**Comment by jonesmz** [comment]
I recommend using boost log

**Comment by jonesmz** [comment]
You can see some decent examples of logging code here: https://github.com/redboltz/mqtt_cpp/issues/292

**Comment by jonesmz** [comment]
Other contributors have recommended https://github.com/gabime/spdlog
