### ISSUE TITLE
Test resource naming with multiple data folders

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#33]
Right now, all the assets are in one big folder, which precludes a lot of name/path issues.

The current way that assets are loaded does not account for situations where two different folders might have a file. The current image loading, for instance, does not disambiguate between images because the resource map uses the filename alone, not the whole path, as the key. This isn't an issue for now, but I just wanted to make a note of it since it'll need to be tackled eventually. It should be pretty easy to build a random, complicated directory structure and fill it with files that have the same name, which should quickly (and spectacularly) reveal what changes need to be made.

**Comment by Capital-Asterisk** [comment]
Not really sure what this issue was originally about, though it's very old and the code base has changed substantially. Most code isn't aware of file paths, and the new resource system is on its way.
