### ISSUE TITLE
Improve SysHierarchy::hierarchy_traverse()

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#40]
"Additionally, consider changing your hierarchy_traverse function to return `decltype(auto)`, and have it return the result of your functor, that would let you change your lambda to return `{EHierarchyTraverseStatus::Stop, ent}` or `{EHierarchyTraverseStatus::Continue, entt::null}`

If you write your function carefully (Or your lambda, depending on how crafty your metaprogramming game is) your `hierarchy_traverse()` function can serve double duty.

In the lazy way, you just always have your `hierarchy_traverse()` function return the second member of the thing returned from the lambda, and for lambdas that don't want to return anything, just have them return like `nullptr` or something.

In the crafty way, you have your `hierarchy_traverse` function return a tuple that represents all of the return values from the lambda except for index 0 (e.g. a tuple suffix).

If you write your `hierarchy_traverse` function carefully, there's very little cost to doing this. E.g. returning a `tuple<EHierarchyTraverseStatus, std::reference_wrapper<>, std::reference_wrapper<>,....>`, where the cost is basically just shuffling pointers around, which the compiler will heavily optimize for you cause of templates.

_Originally posted by @jonesmz in https://github.com/TheOpenSpaceProgram/osp-magnum/pull/36#r552389730_

**Comment by Capital-Asterisk** [comment]
Function moved to `SysHierarchy::traverse` in `osp/Active/SysHierarchy.h`. it is currently not used anywhere.

**Comment by Capital-Asterisk** [comment]
#224 makes this irrelevant
