### ISSUE TITLE
Update DependRes<> to use std::optional<> instead of "m_empty" flag

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#41]
instead of storing an `m_empty` flag in `DependRes<>` to indicate that a resource hasn't been loaded yet, maybe there's room for `std::optional<>` to be used?

_Originally posted by @jonesmz in https://github.com/TheOpenSpaceProgram/osp-magnum/pull/36#discussion_r552378957_

**Comment by Capital-Asterisk** [comment]
Added in #90
