### ISSUE TITLE
Use DependRes's ability to store a not-yet-loaded resource in PlumeEffect; PrototypePart

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#42]
Ideally this [PlumeEffectData::meshName] should be `DependRes`. I'm aware this does have the issue of meshes not being added to the Package yet, but there is a not-yet-implemented solution to this. Note that `osp::Resource<>` has an `m_loaded` bool variable. This is intended to be set false for placeholder resources that are initialized empty. If something needs a resource that isn't loaded yet, it can initialize an empty one, where it can be loaded later.

_Originally posted by @Capital-Asterisk in https://github.com/TheOpenSpaceProgram/osp-magnum/pull/36#discussion_r552235308_

**Comment by Capital-Asterisk** [comment]
Added in #90
