### ISSUE TITLE
Decouple MachineRocket and SysExhaustPlume

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#43]
"...rocket and plumes both depend on each other. Rockets have to initialize the plumes, and plumes are reading MachineRockets specifically.

A possible solution would be to add a new component for plume engine power, in the same entity as MachineRocket. MachineRocket can then write its throttle value into it. This allows other systems aside that aren't rockets to use plumes."

_Originally posted by @Capital-Asterisk in https://github.com/TheOpenSpaceProgram/osp-magnum/pull/36#discussion_r552252877_

**Comment by Capital-Asterisk** [comment]
I thought of another way to do this: add an "update_plumes_from_rockets" function to the update order. This function adds plumes to rockets that don't have them, and updates the plume sizes. Initialization and any other calculations are still done in the update_plumes function.

This is different from my other solution, in a way that it doesn't use generic data to decouple these two systems, but instead keeps the coupling in one place in an explicitly named function.

**Comment by Capital-Asterisk** [comment]
Fixed back in #134
