### ISSUE TITLE
Clean, black window and other flight surprises

### ISSUE THREAD

**Issue by pirogronian** [TheOpenSpaceProgram/osp-magnum#55]
So, after disabling exhaust plumes (although probably most visually fun part of the game), I was able to see main game window... which was essencialy black. Moreover, mouse cursor started to move discontinuously, as with heavy CPU load. It was surprising, as my system monitor displayed CPU load at 1-2%. I tried to click&drag, but the only response was console messages. Clicking to close window worked, but console prompt didnt appeared. But typing "exit" still worked. Here is full console output since `flight` command:

> > flight
> > Platform: can't get Xft.dpi property for virtual DPI scaling, falling back to physical DPI
> Renderer: Mesa DRI Intel(R) HD Graphics 2000 (SNB GT1) by Intel Open Source Technology Center
> OpenGL version: 3.3 (Core Profile) Mesa 20.3.3
> Using optional features:
>     GL_ARB_ES2_compatibility
>     GL_ARB_direct_state_access
>     GL_ARB_get_texture_sub_image
>     GL_ARB_invalidate_subdata
>     GL_ARB_multi_bind
>     GL_ARB_robustness
>     GL_ARB_separate_shader_objects
>     GL_ARB_texture_filter_anisotropic
>     GL_ARB_texture_storage
>     GL_ARB_texture_storage_multisample
>     GL_ARB_vertex_array_object
>     GL_KHR_debug
> Using driver workarounds:
>     no-layout-qualifiers-on-old-glsl
>     mesa-dsa-createquery-except-pipeline-stats
>     mesa-forward-compatible-line-width-range
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> MouseMovementHandle created
> ScrollInputHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> ButtonControlHandle created
> activatin a planet!!!!!!!!!!!!!!!!11
> loadin a vehicle!
> Machine: FreeEnergyGenerator Not found
> Machine: FreeEnergyGenerator Not found
> MachineRocket 13's associated plume: 17
> Machine: FreeEnergyGenerator Not found
> MachineRocket 18's associated plume: 19
> Machine: FreeEnergyGenerator Not found
> MachineRocket 22's associated plume: 23
> Machine: FreeEnergyGenerator Not found
> MachineRocket 26's associated plume: 27
> Machine: FreeEnergyGenerator Not found
> MachineRocket 30's associated plume: 31
> Machine: FreeEnergyGenerator Not found
> MachineRocket 34's associated plume: 35
> Machine: FreeEnergyGenerator Not found
> MachineRocket 38's associated plume: 39
> Machine: FreeEnergyGenerator Not found
> MachineRocket 42's associated plume: 43
> Machine: FreeEnergyGenerator Not found
> MachineRocket 46's associated plume: 47
> Machine: FreeEnergyGenerator Not found
> Connected Throttle to Throttle
> Connected AttitudeControl to Gimbal
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Connected AttitudeControl to Orient
> Connected Throttle to Throttle
> Initializing planet
> Planet initialized, now making colliders
> * completed chunk collider: 0
> * completed chunk collider: 1
> * completed chunk collider: 2
> * completed chunk collider: 3
> * completed chunk collider: 4
> * completed chunk collider: 5
> * completed chunk collider: 6
> * completed chunk collider: 7
> * completed chunk collider: 8
> * completed chunk collider: 9
> * completed chunk collider: 10
> * completed chunk collider: 11
> * completed chunk collider: 12
> * completed chunk collider: 13
> * completed chunk collider: 14
> * completed chunk collider: 15
> * completed chunk collider: 16
> * completed chunk collider: 17
> * completed chunk collider: 18
> * completed chunk collider: 19
> Planet colliders done
> sensitive button pressed
> HOLD
> sensitive button pressed
> RELEASE
> sensitive button pressed
> HOLD
> sensitive button pressed
> RELEASE
> Magnum Application closed
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ScrollInputHandle is dead
> MouseMovementHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> ButtonControlHandle is dead
> 
> 
> exit
> *explosion* Universe destroyed!

I'm glad to be able to help even if only this way. I'm very sad there is virtually nothing open source similar to KSP or Orbiter. In desperation I started my own project recently, but it's very difficult for me to push it forward.

**Comment by z-adams** [comment]
When the scene begins, the camera is just staring off into space. When the scene starts, hit `V` and you should be taken to the first active vessel. KSP-equivalent controls should then be available to control it (LShift/LCtrl to smoothly throttle, Z/X to max/cut throttle, WASD to steer, hole RMB to drag the view). It'll be a bit hard to tell if the engine is running without the engine plume being visible, but the ship should move around. There's not a whole lot to do at this stage as most of our work is engine-level stuff without many visible ramifications, but I'm working on bringing some basic flight features in the coming weeks.

**Comment by pirogronian** [comment]
Indeed, v bring me to the ship, but performance is so poor I'm virtually unable to operate it. I estimated frame rate as 1-2 fps, not more. When window is hided, however, mouse cursor seems to move smoothly. CPU again at 1-2%. Something heavy have to be on shader's side...

**Comment by z-adams** [comment]
What sort of machine are you running on? Is the program compiled in release mode (should be default, but I'm not positive)? We haven't done any sort of performance profiling yet as it's still pretty early.

**Comment by pirogronian** [comment]
CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
RAM: DDR3 4GB
Graphics: Intel HD 2000

Didn't set any additional flag, just `cd build && cmake .. && make`. CMakeCache.txt doesnt seems to have no "DEBUG" value associated to any variable.
[CMakeCache.txt](https://github.com/TheOpenSpaceProgram/osp-magnum/files/5829258/CMakeCache.txt)

Update: using my second card, which is AMD Radeon HD 6738, performance was very good. Although I still have big troubles to control the ship, as it falls onto the planet too quickly and stuck on it with nose buried behind surface... At least I'm sure thrusters works.

**Comment by z-adams** [comment]
Yes, the colliders and general ship physics are very simple at this stage, more to come soon. You just have to get the hang of pressing V and Z as fast as possible and the ship will accelerate past the planet in time. In the coming weeks it should get much more controllable, if I can get my PRs sorted out quickly.

**Comment by pirogronian** [comment]
Understood and waiting... 😄
