### ISSUE TITLE
Get rid of use of `unsigned`

### ISSUE THREAD

**Issue by z-adams** [TheOpenSpaceProgram/osp-magnum#63]
In the interest of platform/multiplayer compatibility, we should get rid of the use of `unsigned` and replace it with `size_t`, or fixed-width `uintxx_t` where appropriate.

_Originally posted by @jonesmz in https://github.com/TheOpenSpaceProgram/osp-magnum/pull/61#discussion_r564215615_

**Comment by EhWhoAmI** [comment]
I'll do this

**Comment by EhWhoAmI** [comment]
Completed with #84
