### ISSUE TITLE
setup vsync in src/test_application/ActiveApplication.h

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/osp-magnum#80]
If vsync can't be enabled, then check settings.toml for a framerate setting.
If no framerate setting is set, then fallback to a max framerate of 120fps.

See here for some relevant documentation

https://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1Sdl2Application.html#a745b3b3793fb1a65e30d1fce72c0625e

**Comment by z-adams** [comment]
Vsync should be on by default, you can disable it with `setSwapInterval(0)` as I've done [here](https://github.com/z-adams/osp-magnum/blob/mapscreen/src/OSPMagnum.cpp#L32) in my mapscreen branch. If you remove that line, the FPS is locked to 60.

**Comment by jonesmz** [comment]
From the documentation for setSwapInterval
```
Default is driver-dependent, you can query the value with swapInterval().
```

So this ticket is for someone to add explicit logic for vsync and falling back to setting the framerate manually.

Combine with https://github.com/TheOpenSpaceProgram/osp-magnum/issues/81 and we can start managing what work to do on which frame.

**Comment by Capital-Asterisk** [comment]
Noting that OSPMagnum.cpp is dead, equivalent file is located in `src/test_application/ActiveApplication.h`

**Comment by Capital-Asterisk** [comment]
Fixed long ago
