### ISSUE TITLE
Get delta from last frame, provide to each system every frame

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/osp-magnum#81]
See for example: https://gist.github.com/alanjfs/a0a9ab4fb4cd808dfd89bc6f2ee3e1af#file-ecsy1-cpp-L226

**Comment by z-adams** [comment]
We currently have an equivalent for getting a fixed 60Hz timestep, but we'll need a dynamic one eventually. In addition, it would also be nice if the application kept a running total of application time (in seconds) that could be accessed by the systems (right now, my systems that are time-dependent (e.g. SysExhaustPlume) have to accumulate the time parameter individually as a member field).

**Comment by Capital-Asterisk** [comment]
Magnum timeline is already used in OSPMagnum. Everything in the physics world should run at a fixed timestep, as a varying timestep can really hurt determinism. Higher framerates should use interpolation.

**Comment by jonesmz** [comment]
Architecturally, this no longer seems relevant.
